include (":app")
rootProject.name = "Android Playground"
include(":core:data")
include(":core:ui")
include(":data:cart")
include(":core:preferences")
include(":data:user")
include(":data:category")
include(":data:product")
include(":feature:cart")
include(":core:util")
