object Versions {
    const val appCompatVersion = "1.2.0"
    const val ktxVersion = "1.3.2"
    const val kotlinVersion = "1.5.0"
    const val materialVersion = "1.3.0"
    const val constraintLayoutVersion = "2.0.4"
    const val retrofitVersion = "2.5.0"
    const val retrofitMoshiConverterVersion = "2.9.0"
    const val moshiVersion = "1.12.0"
    const val navVersion = "2.3.5"
    const val roomVersion = "2.3.0"
    const val interceptorVersion = "4.7.2"
    const val glideVersion = "4.12.0"
    const val hiltVersion = "2.38.1"
    const val lifecycleVersion = "2.4.0"
    const val jUnitXVersion = "1.1.2"
    const val testRunnerVersion = "1.3.0"
    const val truthVersion = "1.1.2"
    const val lottieVersion = "4.2.0"
    const val pagingVersion = "3.1.0"
    const val detektVersion = "1.19.0"
    const val spotlessVersion = "6.0.5"
    const val timberVersion = "5.0.1"
}