name: Testing Workflow

on:
 pull_request:
    branches:
      - master
 push:
     branches:
         - master
jobs:
  testing:
    name: Lint Check and Testing
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'  
          java-version: 11        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Android Ktlint
        run: ./gradlew ktlintCheck
      - name: Run Android Linter
        run: ./gradlew lintDebug
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
